### ISSUE TITLE
Tweak the way headers are set

### ISSUE THREAD

**Issue by vpetersson** [Screenly/cli#41]
Currently, the way we set headers for web assets is as follows:

```bash
$ screenly asset $ASSET_ID set-headers —header k=v
[...]
```

When we do this, we wipe all existing headers in the process. This is somewhat unexpected.

An alternative approach is to add the following `headers` sub-commands:

* add
  * Adds on or more headers (passed on as comma separated key-value pairs)
* remove 
  * Removes on or more headers (passed on as comma separated key-value pairs)
* update
  * Updates on or more headers (passed on as comma separated key-value pairs)
* clear
  * Removes all headers

An alternative approach would be something like this:

```bash
$ screenly asset $ASSET_ID headers add k=v,foo=bar
[...]
```

If you then just want to update say the key `k`, you can use 

```bash
$ screenly asset $ASSET_ID headers update k=foobar
[...]
```

This is open for debate, but I think this would be more user friendly.

**Comment by aljungberg** [comment]
Great write-up. Here's my take, two things.

First, not sure we should split this subcommand into two words (`headers add` versus `add-headers`). Barring any good reasons to deviate, I'd like to stay consistent with the `gcloud` command as a kind of best practice or "industry standard". And they don't split the operations. For example they have `add-tags` and `remove-tags`:

```
➜  ~ gcloud compute instances --help | rg tags
     add-tags
        Add tags to Compute Engine virtual machine instances.
     remove-tags
        Remove tags from Compute Engine virtual machine instances.
```

That said, allow me to immediately deviate from `gcloud` (they don't do what I'm about to propose, but neither do they do what Viktor proposed as you see above).

I think the use case of wanting to clobber all existing headers is valid and less surprising in some cases. Like if I have a cron job to update an asset with a new set of authorise headers or whatever every day due to security rotation, maybe something weird where even the header names change, it would be far easier to just set exactly what I want in one go, knowing all old headers are properly gone at the same time.

My set of commands would be like this:

- `set-headers [header1=value1[,header2=value2[,...]]]`: replaces all headers of the asset with the given headers (when an empty string is given, e.g. `--set-headers ""`, all existing headers are removed, if any)
- `update-headers <header1=value1[,header2=value2[,...]]>`: updates only the given headers (adding them if new), leaving any other headers unchanged

One elegant bit is that we don't need separate `add` or `clear` variants in this case:

- you can add with `update` 
- and clear with `set-headers` 

I like this because both subcommands are idempotent. Like you can call `update` twice in a row and the result is the same as calling it once, whereas with `add` I'd expect the second call to crash with a `header already exists; use update instead` error. And `set-headers` is race condition safe too, handling edge cases like if some script adds a header in between your `clear` and `update` commands, leading to a set of headers neither you nor the script wanted. That can't happen with `set-headers`: either your headers go or the script's but never a Frankenstein's mix of both.

**Comment by vpetersson** [comment]
I'm OK with this, but it will be somewhat inconsistent with how we are going to deal with secrets/env variables I guess. If we're fine with being inconsistent, then sure.
